{% set name = "diff-cover" %}
{% set version = "7.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/diff_cover-{{ version }}.tar.gz
  sha256: d1007303f6bfba14925f602fc735ca8d6b254d8b57320f2b4b38a3a618453f40

build:
  noarch: python
  number: 0
  entry_points:
    - diff-cover = diff_cover.diff_cover_tool:main
    - diff-quality = diff_cover.diff_quality_tool:main
  script: '{{ PYTHON }} -m pip install . --no-deps -vv '

requirements:
  host:
    - pip
    - poetry
    - python >=3.7.2
  run:
    - jinja2 >=2.7.1
    - pluggy >=0.13.1,<2
    - pygments >=2.9.0
    - python >=3.7.2
    - chardet >=3.0.0
    - setuptools >=17.0

  run_constrained:
    - tomli >=1.2.1

test:
  imports:
    - diff_cover
    - diff_cover.violationsreporters
  commands:
    - diff-cover --help
    - diff-quality --help

about:
  home: https://github.com/Bachmann1234/diff-cover
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Automatically find diff lines that need test coverage.

extra:
  recipe-maintainers:
    - nicoddemus
